### ISSUE TITLE
Make error term for ubiquitous search term

### ISSUE THREAD

**Issue by ckbrinkley** [Hack-for-California/General-Plan-Map#10]
Cannot search for ‘plan’ ‘area’ ‘land’ or ‘city’- get booted out of server

**Comment by lindsaypoirier** [comment]
Archiving the troubleshooting of this for others!

Words like general, land, and city appear in all of the plans. When we search for a word, the map both changes the polygon colors of the cities who reference the word blue, and the cities that don't reference the word pink. If there are no cities that don't reference the word, the map is trying to change zero polygons pink, which causes the server boot. 

The solution to this on my local machine was to first check if there were cities that don't reference the word with an if statement:
`if(nrow(to_clear) !=0` # add the blue polygons; else don't add them

This worked locally, but the remote shiny server logged the error:
`Warning: Error in matrix: length of 'dimnames' [2] not equal to array extent
  75: matrix
  74: Ops.data.frame
  72: observeEventHandler [/srv/shiny-server/general-plan-map/R/shiny_app/server.R#101]
   1: runApp`

We updated that if statement to:
`if(dim(to_clear)[1] != 0)`

...which seemed to fix the issue.

**Comment by ckbrinkley** [comment]
Yay! thank you


Catherine Brinkley, VMD, PhD, MS
Associate Professor
College of Agricultural and Environmental Sciences
Office: 2333 Hart Hall
University of California, Davis



Recent work
Cities as Coral Reefs, in Annals of the American Association of Geographers<https://www.tandfonline.com/doi/full/10.1080/24694452.2019.1573133>

What makes a supermarket intervention successful in a food desert? in Journal of Public Affairs<https://onlinelibrary.wiley.com/doi/full/10.1002/pa.1863>

Energy next door: a meta-analysis of energy infrastructure impact on housing value, in Energy Research & Social Science<https://www.sciencedirect.com/science/article/pii/S2214629618300495>

Podcast on One Health<https://anchor.fm/miis-radio/episodes/The-Implications-Episode-1-Dr--Catherine-Brinkley-and-One-Health-eb2j45>
<https://www.sciencedirect.com/science/article/pii/S2214629618300495>



________________________________
